function(setup_static_analysis)
	find_program(CLANG_TIDY clang-tidy)
	if(CLANG_TIDY)
		message(STATUS "clang-tidy found: ${CLANG_TIDY}")
		set(CMAKE_CXX_CLANG_TIDY ${CLANG_TIDY} PARENT_SCOPE)
	else()
		message(WARNING "clang-tidy not found")
	endif()
endfunction()
